version: '3.1'

services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=danube
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=danube
  redis:
    image: redis:6
    ports:
      - 6379:6379
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=secret
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=danube.settings
      - ALLOWED_HOSTS=*
      - DB_NAME=danube
      - DB_PASSWORD=postgres
      - DB_USER=danube
      - DB_HOST=postgres
      - DB_PORT=5432
      - STRIPE_SECRET_KEY=sk_live_stripe_key
      - STRIPE_TEST_SECRET_KEY=sk_test_stripe_key
      - SECURE_SSL_REDIRECT=false
      - REDIS_URL=redis://:@redis:6379/0
volumes:
  templates: