# Generated by Django 3.1.2 on 2022-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Mr"),
                    (2, "Ms"),
                    (3, "Mrs"),
                    (4, "Dr"),
                    (5, "Miss"),
                    (6, "Them"),
                    (7, "They"),
                    (8, "He"),
                    (9, "She"),
                ],
                null=True,
            ),
        ),
        migrations.DeleteModel(name="Title",),
    ]
