# Generated by Django 3.1.2 on 2022-07-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_auto_20220713_1357"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="surname", new_name="last_name",
        ),
    ]
