# Generated by Django 3.1.2 on 2022-07-26 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0005_auto_20220714_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "vat",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="VAT number",
                        max_length=12,
                        null=True,
                    ),
                ),
                ("main_trade", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "companies_house_number",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d+(?:\\d+)*\\Z"),
                                code="invalid",
                                message=None,
                            ),
                            django.core.validators.MinLengthValidator(8),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Details",
                "ordering": ["-created_at"],
            },
        ),
    ]
