# Generated by Django 3.1.2 on 2022-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_auto_20220726_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address_2",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="town",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
