# Generated by Django 3.1.2 on 2022-07-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0008_auto_20220728_1305"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessdetails",
            name="address_1",
            field=models.CharField(default="Default", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessdetails",
            name="address_2",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="businessdetails",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="businessdetails",
            name="county",
            field=models.CharField(default="Default", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessdetails",
            name="postcode",
            field=models.CharField(default="Default", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessdetails",
            name="town",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessdetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
    ]
