# Generated by Django 4.1 on 2022-09-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20220731_1816"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
