# Generated by Django 3.1.2 on 2022-08-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0009_auto_20220731_1816"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "DRAFT"),
                            (2, "NEW"),
                            (3, "OPEN"),
                            (4, "ISSUED"),
                            (5, "CONTRACTED"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property",
                        to="profiles.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RFQItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_of_work", models.CharField(blank=True, max_length=30)),
                ("brief_description", models.CharField(blank=True, max_length=200)),
                ("detailed_description", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfq_items",
                        to="quotes.rfq",
                    ),
                ),
            ],
        ),
    ]
