# Generated by Django 3.1.2 on 2022-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfq", name="title", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="rfqitem",
            name="area_of_work",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="rfqitem",
            name="brief_description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="rfqitem",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rfqitem", name="detailed_description", field=models.TextField(),
        ),
    ]
