# Generated by Django 4.1 on 2022-08-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20220731_1816"),
        ("quotes", "0003_alter_rfq_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfq",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "DRAFT"),
                    (2, "SAVED"),
                    (3, "OPEN"),
                    (4, "PRIVATE"),
                    (5, "CONTRACTED"),
                    (6, "ARCHIVED"),
                    (7, "COMPLETED"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="RFQBusinessRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(1, "WAITING"), (2, "CLOSED"), (3, "ARCHIVED")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_request",
                        to="profiles.businessdetails",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_request",
                        to="quotes.rfq",
                    ),
                ),
            ],
        ),
    ]
