# Generated by Django 4.1 on 2022-08-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20220731_1816"),
        ("quotes", "0005_alter_rfq_property"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rfqbusinessrequest", unique_together={("rfq", "business_profile")},
        ),
    ]
