# Generated by Django 4.1 on 2022-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_eoi"),
    ]

    operations = [
        migrations.AddField(
            model_name="eoi",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
