# Generated by Django 4.1 on 2022-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_eoi_start_price_alter_rfqbusinessrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eoi",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(1, "NEW"), (2, "ACCEPTED"), (3, "DECLINED")], default=1
            ),
        ),
    ]
