# Generated by Django 4.1 on 2022-10-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_eoi_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eoi',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='rfqbusinessrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='rfqitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
