# Generated by Django 3.1.2 on 2022-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20220622_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "Customer"), (2, "Business"), (3, "Employee")],
                null=True,
            ),
        ),
    ]
