# Generated by Django 3.1.2 on 2022-07-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20220712_1434"),
    ]

    operations = [
        migrations.DeleteModel(name="UserType",),
    ]
