# Generated by Django 3.1.2 on 2022-08-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveIntegerField(
                choices=[(1, "Customer"), (2, "Business"), (3, "Employee")], default=1
            ),
        ),
    ]
