# Generated by Django 4.1 on 2022-09-14 10:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20220805_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                default="12345678901",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:\\d+)*\\Z"), code="invalid", message=None
                    ),
                    django.core.validators.MinLengthValidator(11),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "Mr"),
                    (2, "Ms"),
                    (3, "Mrs"),
                    (4, "Dr"),
                    (5, "Miss"),
                    (6, "Them"),
                    (7, "They"),
                    (8, "He"),
                    (9, "She"),
                ],
                null=True,
            ),
        ),
    ]
