# Generated by Django 3.1.2 on 2022-06-09 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=ckeditor.fields.RichTextField(help_text="Testimonial's content"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(
                help_text="Testimonial's owner name", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="title",
            field=models.CharField(help_text="Job title", max_length=250),
        ),
    ]
