# Generated by Django 3.1.2 on 2022-06-10 15:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_auto_20220609_1454"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="Question text", max_length=500),
                ),
                (
                    "answer",
                    ckeditor.fields.RichTextField(help_text="Answer to the question."),
                ),
            ],
        ),
    ]
