# Generated by Django 3.1.2 on 2022-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(help_text="Answer to the question."),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=models.TextField(help_text="Testimonial's content"),
        ),
    ]
