# Generated by Django 3.1.2 on 2022-06-17 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_auto_20220613_2238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor.fields.RichTextField(help_text="Answer to the question."),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="content",
            field=ckeditor.fields.RichTextField(help_text="Testimonial's content"),
        ),
    ]
