# Generated by Django 4.1 on 2022-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'OPEN'), (2, 'PENDING'), (3, 'PAID')], default=1),
        ),
    ]