# Generated by Django 4.1 on 2022-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danube', '0003_alter_invoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
