# Generated by Django 4.1 on 2022-08-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quotes", "0010_alter_eoi_status"),
        ("profiles", "0009_auto_20220731_1816"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "DRAFT"),
                            (2, "WAITING"),
                            (3, "IN_PROGRESS"),
                            (4, "DONE"),
                            (5, "REJECTED"),
                        ],
                        default=1,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="profiles.businessdetails",
                    ),
                ),
                (
                    "eoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="quotes.eoi",
                    ),
                ),
                (
                    "property_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="profiles.property",
                        verbose_name="property",
                    ),
                ),
            ],
            options={"unique_together": {("business", "eoi")},},
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True, null=True)),
                ("include_in_first_payment", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
