# Generated by Django 4.1 on 2022-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
