# Generated by Django 4.1 on 2022-10-11 17:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='discount_type',
            field=models.PositiveIntegerField(choices=[(1, 'PERCENT'), (2, 'AMOUNT')], default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
