# Generated by Django 4.1 on 2022-10-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_discount_contract_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='include_in_first_payment',
        ),
    ]
