# Generated by Django 4.1 on 2022-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='business_completed',
            field=models.BooleanField(default=False),
        ),
    ]
