# Generated by Django 4.1 on 2022-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_business_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_payment_paid',
            field=models.BooleanField(default=False),
        ),
    ]
