# Generated by Django 4.1 on 2022-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_first_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='first_payment_paid_business',
            field=models.BooleanField(default=False),
        ),
    ]
